apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-python-ingress
  labels:
    name: my-python-ingress
spec:
  rules:
  - host: my-python.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: my-python
            port: 
              number: 8889
